# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"

    schedule:
      interval: "monthly"

    open-pull-requests-limit: 10
    versioning-strategy: increase
    commit-message:
      prefix: "chore: "

    groups:
      commitlint:
        patterns:
          - "@commitlint/*"
      conform-to:
        patterns:
          - "@conform-to/*"
      prisma:
        patterns:
          - "prisma"
          - "@prisma/*"
      remix:
        patterns:
          - "@remix-run/*"
      react:
        patterns:
          - "react"
          - "react-dom"
      testing-library:
        patterns:
          - "@testing-library/*"
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"
