# Based on https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/automating-projects-using-actions
name: 🗂 Set issue status
on:
  issues:
    types: [assigned, unassigned]
jobs:
  track_pr:
    name: Set to 🏗 In Progress / 🔖 Ready
    runs-on: ubuntu-latest
    steps:
      - name: Get project data
        env:
          GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}
          USER: ${{github.repository_owner}}
          PROJECT_NUMBER: 2
          ISSUE_ID: ${{ github.event.issue.node_id   }}
        run: |
          gh api graphql -f query='
            query($user: String!, $number: Int!, $issue:ID!) {
              node(id: $issue) {
                ... on Issue {
                  projectItems(first:1) {
                    nodes {
                      id
                    }
                  }
                }
              }
              user(login: $user){
                projectV2(number: $number) {
                  id
                  fields(first:20) {
                    nodes {
                      ... on ProjectV2Field {
                        id
                        name
                      }
                      ... on ProjectV2SingleSelectField {
                        id
                        name
                        options {
                          id
                          name
                        }
                      }
                    }
                  }
                }
              }
            }' -f user=$USER -F number=$PROJECT_NUMBER -f issue=$ISSUE_ID > project_data.json

          echo 'PROJECT_ID='$(jq '.data.user.projectV2.id' project_data.json) >> $GITHUB_ENV
          echo 'STATUS_FIELD_ID='$(jq '.data.user.projectV2.fields.nodes[] | select(.name== "Status") | .id' project_data.json) >> $GITHUB_ENV
          # Using jq -r here because IN_PROGRESS_OPTION_ID is an Int and we need to keep it like that instead of letting jq return a String
          echo 'IN_PROGRESS_OPTION_ID='$(jq -r '.data.user.projectV2.fields.nodes[] | select(.name== "Status") | .options[] | select(.name=="🏗 In progress") |.id' project_data.json) >> $GITHUB_ENV
          echo 'READY_OPTION_ID='$(jq -r '.data.user.projectV2.fields.nodes[] | select(.name== "Status") | .options[] | select(.name=="🔖 Ready") |.id' project_data.json) >> $GITHUB_ENV
          echo 'LINKED_ISSUE_ID='$(jq '.data.node.projectItems.nodes[0].id' project_data.json) >> $GITHUB_ENV

      - name: Move to 🏗 In Progress
        if: ${{ toJson(github.event.issue.assignees.*.login) != 'null' }}
        env:
          GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}
        run: |
          echo 'Move to 🏗 In Progress'
          gh api graphql -f query='
            mutation (
              $project: ID!
              $item: ID!
              $status_field: ID!
              $status_value: String!
            ) {
              updateProjectV2ItemFieldValue(input: {
                projectId: $project
                itemId: $item
                fieldId: $status_field
                value: {
                  singleSelectOptionId: $status_value
                }
              }) {
                projectV2Item {
                  id
                }
              }
            }' -f project=$PROJECT_ID -f item=$LINKED_ISSUE_ID -f status_field=$STATUS_FIELD_ID -f status_value=$IN_PROGRESS_OPTION_ID

      - name: Move to 🔖 Ready
        if: ${{ toJson(github.event.issue.assignees.*.login) == 'null' }}
        env:
          GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}
        run: |
          echo 'Move to 🔖 Ready'
          gh api graphql -f query='
            mutation (
              $project: ID!
              $item: ID!
              $status_field: ID!
              $status_value: String!
            ) {
              updateProjectV2ItemFieldValue(input: {
                projectId: $project
                itemId: $item
                fieldId: $status_field
                value: {
                  singleSelectOptionId: $status_value
                }
              }) {
                projectV2Item {
                  id
                }
              }
            }' -f project=$PROJECT_ID -f item=$LINKED_ISSUE_ID -f status_field=$STATUS_FIELD_ID -f status_value=$READY_OPTION_ID
